#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG_FILE=$1

branch_name=`git rev-parse --abbrev-ref HEAD`
branch_prefix=`echo ${branch_name} | cut -f1 -d '/'`
issue_number1=`echo ${branch_name} | cut -f2 -d '/' | cut -f1 -d '_'`
issue_number2=`echo ${branch_name} | cut -f2 -d '/' | cut -f1 -d '-'`
first_line=`head -n1 ${COMMIT_MSG_FILE}`

number_re='^[0-9]+$'
issue_re='#[0-9]+'

if [[ $issue_number1 =~ $number_re ]]; then
    issue_number=$issue_number1
elif [[ $issue_number2 =~ $number_re ]]; then
    issue_number=$issue_number2
fi

echo Issue number: $issue_number
echo COMMIT_MSG_FILE: $COMMIT_MSG_FILE # COMMIT_MSG_FILE: .git/COMMIT_EDITMSG
echo first_line: $first_line

repo='oneweek-template'

web='web'
app='app'
server='server'
pkg='pkg'
package='package'

common="common"
feature="feature"

if [[ $issue_number =~ $number_re ]];
then
    if [ "$branch_prefix" == "$web" ]; then
        part_name="web"
	elif [ "$branch_prefix" == "$app" ]; then
        part_name='app'
	elif [ "$branch_prefix" == "$server" ]; then
        part_name='server'
	elif [ "$branch_prefix" == "$pkg" ] || [ "$branch_prefix" == "$package" ]; then
        part_name='packages'
    elif [ "$branch_prefix" == "$feature" ] || [ "$branch_prefix" == "$common" ]; then
        part_name='common'
    fi

    sed -i.bak "1s/${first_line}/[$part_name] #$issue_number $first_line/" $COMMIT_MSG_FILE
    exit 0
fi
